all:
  children:
    servers:
      hosts:
        k3s-server:
          ansible_host: 192.168.68.121
    agents:
      hosts:
        k3s-agent:
          ansible_host: 192.168.68.114
  vars:
    ansible_user: rob
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    k3s_server_ip: 192.168.68.121
